### ISSUE TITLE
Some other open source projects that might be useful removing malwares caused by these scams

### ISSUE THREAD

**Issue by Git-North** [0NETAP/DMV#5]
Hello! I just wanted to link a few open source projects that might be useful removing malwares since any external application downloaded by discord (looking at you _beta testing scam_)

## [Tron-Script](https://github.com/bmrf/tron/)
`Tron` is a powerful tool that is basically a lot of batch files that automates the process of disinfecting your windows machine

<details><summary>Here's a list of resources related to Tron</summary>
<p>
- [Download it here](https://www.reddit.com/r/TronScript/wiki/downloads)
- [The official Reddit page](https://old.reddit.com/r/TronScript/wiki/index)
- [Github for source code](https://github.com/bmrf/tron)
- Tron-Script seems to be using Reddit as their main page

</p>
</details>

## [Process Hacker](https://processhacker.sourceforge.io/)
`Process Hacker` is like an advanced task manager it will help you find paranormal activties and terminate and suspend them

<details><summary>Here's a list of resources related to Process Hacker </summary>
<p>

- [Download it here](https://processhacker.sourceforge.io/nightly.php)
- [The official page](https://processhacker.sourceforge.io/)
- [Github for source code](https://processhacker.sourceforge.io/github.php)
- Sadly I could not find a reddit page dedicated to Process Hacker

</p>
</details>

**Comment by addi00000** [comment]
I'll add in a bit if I can or you can make a pr and it will be merged.

**Comment by Git-North** [comment]
Will do

**Comment by Git-North** [comment]
done

**Comment by Git-North** [comment]
- [x] #6
